//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCopy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookCopy()
        {
            this.Rents = new HashSet<Rent>();
        }

        public Rent getLastRent()
        {
            if (this.Rents.Count == 0)
                return null;

            Rent max = new Rent();
            max.RentID = 0;
            foreach (Rent rent in this.Rents)
            {
                if (rent.RentID > max.RentID)
                    max = rent;
            }
            return max;
        }

        public bool isAvailable()
        {
            Rent lastRent = this.getLastRent();
            return lastRent == null ? true : lastRent.IsReturned;
        }

        public int CopyID { get; set; }
        public int BookID { get; set; }
        public int PublisherID { get; set; }
        public Nullable<int> Pages { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
