//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rent : IValidatableObject
    {
        public int RentID { get; set; }
        
        [Required]
        public int CopyID { get; set; }
        
        [Required]
        public int CustomerID { get; set; }
        
        [Required]
        public System.DateTime DateStart { get; set; }
        
        [Required]
        [Display(Name = "End date")]
        public System.DateTime DateEnd { get; set; }
        public bool IsReturned { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
    
        public virtual BookCopy BookCopy { get; set; }
        public virtual Customer Customer { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (DateStart > DateEnd)
            {
                yield return new ValidationResult(
                    $"End date of rent can't be set earlier than date of start.",
                    new[] { nameof(DateEnd) });
            }
        }
    }
}
