//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int RentID { get; set; }
        public int CopyID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public bool IsReturned { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
    
        public virtual BookCopy BookCopy { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
